# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('get_posts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='dashboard1.User')),
                ('send_posts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='dashboard1.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard1.User')),
            ],
        ),
    ]
