# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='user_id',
            new_name='user_link',
        ),
    ]
