# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buyer_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller_link',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
