# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friends_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friends', models.ManyToManyField(default=None, related_name='is_friends_with', to='friends_one.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_friends', to='friends_one.User')),
            ],
        ),
    ]
