# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mylibrary2', '0001_initial'),
        ('mylibrary1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booknote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mybook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mylibrary2.Book')),
                ('owner_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mybooklink', to='mylibrary1.User')),
            ],
        ),
        migrations.CreateModel(
            name='Readbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_toread_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mylibrary2.Book')),
                ('reader_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readers', to='mylibrary1.User')),
            ],
        ),
        migrations.AddField(
            model_name='booknote',
            name='mybook_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booknotes', to='mylibrary3.Mybook'),
        ),
        migrations.AddField(
            model_name='booknote',
            name='readbook_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readnotes', to='mylibrary3.Readbook'),
        ),
    ]
