# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybook',
            name='book_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mybooks', to='mylibrary2.Book'),
        ),
        migrations.AlterField(
            model_name='mybook',
            name='owner_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerlink', to='mylibrary1.User'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='book_toread_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readbooks', to='mylibrary2.Book'),
        ),
    ]
