# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('quote', models.CharField(max_length=255)),
                ('add_id', models.ManyToManyField(related_name='addquotes', to='quotes_one.User')),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes_one.User')),
            ],
        ),
    ]
